blog/urls.py
# blog urls.py

from django.urls import path
from blog.views import BlogListView, BlogDetailView, BlogCreateView, BlogUpdateView, BlogDeleteView

app_name = 'blog'

urlpatterns = [
    path("blog_list/", BlogListView.as_view(), name="blog_list"),
    path("blog/<int:pk>/", BlogDetailView.as_view(), name="blog_detail"),
    path("blog/create", BlogCreateView.as_view(), name="blog_create"),
    path("blog/<int:pk>/update", BlogUpdateView.as_view(), name="blog_create"),
    path("blog/<int:pk>/delete", BlogDeleteView.as_view(), name="blog_confirm_delete"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("catalog.urls", namespace="catalog")),
    path("blog/", include("blog.urls", namespace="blog")),
    path("users/", include("users.urls", namespace="users")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

class Blog(models.Model):
    """
    Модель таблицы blog.
    """
    title = models.CharField(max_length=255, verbose_name="Название статьи")
    content = models.TextField(verbose_name="Содержимое")
    preview = models.ImageField(verbose_name="Миниатюра", blank=True, null=True, upload_to="blog/")
    created_at = models.DateField(auto_now_add=True, verbose_name="Дата создания")
    publicated = models.BooleanField(default=False, verbose_name="Признак публикации")
    views_counter = models.PositiveIntegerField(default=0, verbose_name="Количество просмотров")

    def __str__(self):
        return self.title

    def __repr__(self):
        return f"{self.__class__} {self.title}"

    class Meta:
        verbose_name = "Блог"
        verbose_name_plural = "Блоги"
        ordering = ("-created_at",)

blog/forms.py
import os

from blog.mixins import StyledFormMixin
from django import forms
from django.core.exceptions import ValidationError
from dotenv import load_dotenv

from blog.models import Blog

load_dotenv()
                

class BlogForm(StyledFormMixin, forms.ModelForm):
    class Meta:
        model = Blog
        fields = "__all__"
        labels = {
            "title": "Название статьи",
            "content": "Содержимое",
            "preview": "Миниатюра",
            "created_at": "Дата создания",
            "publicated": "Признак публикации",
            "views_counter": "Количество просмотров",
        }
    
    # Закоментированный ниже код заменяем на класс-миксин
    # def __init__(self, *args, **kwargs):
    #     """Осуществляет стилизацию формы."""
    #     super(BlogForm, self).__init__(*args, **kwargs)
    #
    #     for _, field in self.fields.items():
    #         if isinstance(field, forms.BooleanField):
    #             field.widget.attrs.update(
    #                 {
    #                     "class": "form-check-input",
    #                 }
    #             )
    #         else:
    #             field.widget.attrs.update(
    #                 {
    #                     "class": "form-control",
    #                     "placeholder": field.label,
    #                     "style": "font-size: 0.9em; width: 100%",
    #                 }
    #             )

    def clean_image_format(self):
        """
        Проверяет, что загружаемое изображение продукта в формате .jpg или .png.
        """
        image = self.cleaned_data.get("image")
        if image:
            valid_extensions = [".jpg", ".jpeg", ".png"]
            ext = os.path.splitext(image.name)[1].lower()
            if ext not in valid_extensions:
                raise ValidationError(
                    "Допустимые форматы изображений: .jpg, .jpeg, .png."
                )

        return image

    def clean_image_size(self):
        """
        Проверяет, что загружаемый файл изображения не превышает 5 МБ.
        """
        image = self.cleaned_data.get("image")
        max_size = 5 * 1024 * 1024  # 5 MБ

        if image and image.size > max_size:
            raise ValidationError("Размер изображения не должен превышать 5 МБ.")

        return image

    def clean(self):
        """Проверяет, что указанные поля формы не содержат запрещённые слова."""
        forbidden_words = os.getenv("FORBIDDEN_WORDS").split(",")
        cleaned_data = super().clean()
        cleaned_title = cleaned_data.get("title").split()
        for word in cleaned_title:
            if word.lower() in forbidden_words:
                self.add_error(
                    "title",
                    "Поле с названием статьи содержит запрещённое слово %s." % word,
                )
                break

        cleaned_content = cleaned_data.get("content")
        for word in forbidden_words:
            if word in cleaned_content:
                self.add_error(
                    "content", "Статья содержит запрещённое слово %s." % word
                )
                break

        return cleaned_data

blog/views.py
# blog/views.py
import logging

from django.urls import reverse_lazy

from django.core.mail import send_mail
from blog.forms import BlogForm
from blog.models import Blog
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin

from dotenv import load_dotenv

load_dotenv()

logger = logging.getLogger("blog")
logger.setLevel(logging.DEBUG)
handler = logging.FileHandler("blog/logs/reports.log", "a", "utf-8")
handler.setFormatter(logging.Formatter("%(asctime)s - %(name)s - %(levelname)s: %(message)s"))
logger.addHandler(handler)


class BlogListView(ListView):
    """Определяет отображение страницы блога."""

    model = Blog
    context_object_name = "blog_list"

    def get_queryset(self):
        """Возвращает только опубликованные статьи."""
        return Blog.objects.filter(publicated=True)


class BlogDetailView(LoginRequiredMixin, DetailView):
    """Определяет отображение страницы с содержимым статьи."""

    model = Blog

    def get_object(self, queryset=None):
        """Проверяет количество просмотров статьи и отправляет уведомление администратору."""
        self.object = super().get_object(queryset)
        self.object.views_counter += 1

        # Отправлять уведомление администратору, если количество просмотров превысило 100
        if self.object.views_counter >= 100:
            logger.info("Количество просмотров превысило %s." % self.object.views_counter)
            self.send_info_email("stasm226@gmail.com")
            logger.info("Информационное сообщение отправлено на адрес %s." % "stasm226@gmail.com")

        self.object.save()

        return self.object

    def send_info_email(self, user_email):
        """Отправляет сообщение на email пользователя при успешной регистрации."""
        subject = "Новое достижение!"
        message = "Количество просмотров превысило 100: %s" % self.object.views
        from_email = "stasm226@gmail.com"
        recipients = ["stasm226@gmail.com"]
        send_mail(subject, message, from_email, recipients)


class BlogCreateView(LoginRequiredMixin, CreateView):
    """Определяет отображение страницы добавления статьи."""

    model = Blog
    form_class = BlogForm
    success_url = reverse_lazy("blog:blog_list")

    def form_valid(self, form):
        """Дополнительная обработка перед сохранением формы."""
        self.object = form.save()  # Сохраняем объект формы в базу
        logger.info("Статья '%s' успешно создана." % self.object.title)
        return super().form_valid(form)

    def form_invalid(self, form):
        """Обработка в случае неверной формы."""
        logger.warning("Ошибка при создании статьи: %s" % form.errors)
        return super().form_invalid(form)


class BlogUpdateView(LoginRequiredMixin, UpdateView):
    """Определяет отображение обновления статьи."""

    model = Blog
    form_class = BlogForm
    success_url = reverse_lazy("blog:blog_list")

    def form_valid(self, form):
        """Дополнительная обработка перед сохранением формы."""
        self.object = form.save()  # Сохраняем объект формы в базу
        logger.info("Статья '%s' успешно обновлена." % self.object.title)
        return super().form_valid(form)

    def form_invalid(self, form):
        """Обработка в случае неверной формы."""
        logger.warning("Ошибка при обновлении статьи: %s" % form.errors)
        return super().form_invalid(form)

    def get_success_url(self):
        """Возвращает URL для перехода на страницу с содержимым статьи после успешного удаления."""
        return reverse_lazy("blog:blog_detail", kwargs={"pk": self.object.pk})


class BlogDeleteView(LoginRequiredMixin, DeleteView):
    """Определяет отображение удаления статьи."""

    model = Blog
    form_class = BlogForm
    success_url = reverse_lazy("blog:blog_list")

    def post(self, request, *args, **kwargs):
        """Переопределение метода POST для вызова delete."""
        logger.info("Удаление статьи через POST-запрос.")
        return self.delete(request, *args, **kwargs)

    def delete(self, request, *args, **kwargs):
        """Переопределение метода delete для логирования."""
        blog = self.get_object()
        logger.info("Статья '%s' успешно удалена." % blog.title)
        return super().delete(request, *args, **kwargs)

blog/templates/blog/blog_confirm_delete.html
<!-- blog_confirm_delete.html -->
{% extends 'base.html' %}
{% block title %}
  Блог
{% endblock %}
{% block content %}
  {% include 'header.html' %}
  {% include 'navbar.html' %}

  <div class="container">
    <div class="row" style="align-items: center; justify-content: center;">
      <div class="col-8">
        <form class="row" method="post" enctype="multipart/form-data">
          <div class="card">
            <div class="card-body">
              {% if blog.preview %}
                <img src="{{ blog.preview.url }}" alt="{{ blog.title }}" style="max-width: 800px;"/>
              {% else %}
                <img src="/media/blog/blog_default.png" alt="{{ blog.title }}" style="max-width: 800px;"/>
              {% endif %}
              <h4>{{ blog.title }}</h4>
              <br/>
              <h4>Удалить статью?</h4>
              {% csrf_token %}
            </div>
            <div class="btn-group" style="width: 50%">
              <button type="submit" class="btn btn-danger">Удалить</button>
              <a href="{% url 'blog:blog_list' %}" class="btn btn-secondary">Отменить</a>
            </div>
            <br/>
          </div>
        </form>
      </div>
    </div>
  </div>

{% endblock %}

blog/templates/blog/blog_detail.html
<!-- blog_detail.html -->
{% extends 'base.html' %}
{% block title %}
  Блог
{% endblock %}
{% block content %}
  {% include 'header.html' %}
  {% include 'navbar.html' %}

  <div class="container text-start col-10">
    <div class="container-lg-fluid mt-5">
      <div class="container-fluid text-black">
        <h4 class="mb-4 text-opacity-75 fw-bold">{{ object.title }}</h4>
        <div class="row">
          <div class="col">
            <p style="color: #adb5bd; font-size: 0.9em;">Дата создания: {{ blog.created_at|date:'d.m.Y' }}</p>
          </div>
          <div class="col">
            <p style="color: #adb5bd;font-size: 0.9em;">Количество просмотров: {{ blog.views_counter }}</p>
          </div>
        </div>
        <div class="justify-content-start">
          {% if blog.preview %}
            <img src="{{ blog.preview.url }}" alt="{{ blog.preview }}" style="max-width: 800px;"/>
          {% else %}
            <img src="/media/blog/blog_default.png" alt="{{ blog.preview }}" style="max-width: 800px;"/>
          {% endif %}
        </div>
        <br/>
      </div>
      <p>{{ object.content }}</p>
      <br/>
      <div class="btn-group">
        <a href="{% url 'blog:blog_list' %}" class="btn btn-secondary">Вернуться</a>
      </div>
    </div>
  </div>

{% endblock %}

blog/templates/blog/blog_form.html
<!-- blog_form.html -->
{% extends 'base.html' %}
{% block title %}
Skystore
{% endblock %}
{% block content %}
{% include 'header.html' %}
{% include 'navbar.html' %}

<div class="container">
    <div class="row" style="align-items: center; justify-content: center;">
        <div class="col-8">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="card">
                    <div class="card-body">
                        {% if blog.preview %}
                        <img src="{{ blog.preview.url }}" alt="{{ blog.title }}" style="max-width: 800px;"/>
                        {% endif %}
                        {% csrf_token %}
                        {{ form.non_field_error }}
                        {{ form.as_p }}
                    </div>
                    <div class="btn-group" style="width: 50%">
                        <button type="submit" class="btn btn-primary">Сохранить</button>
                        <a href="{% url 'blog:blog_list' %}" class="btn btn-secondary">Отменить</a>
                    </div>
                    <br/>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

blog/templates/blog/blog_list.html
<!-- blog_list.html -->
{% extends 'base.html' %}
{% block title %}
Skystore
{% endblock %}
{% block content %}
{% include 'header.html' %}
{% include 'navbar.html' %}

<!-- Заголовок страницы -->
<div class="pricing-header px-3 py-3 pt-md-1 pb-md-4 mx-auto text-center">
  <div class="row">
    <div class="col-10">
      <p class="text-start" style="font-size: 1.2em;">Отличный вариант поделиться впечатлениями о товаре или
        работе сервиса</p>
    </div>
    <div class="col-2">
      {% if user.is_authenticated %}
      <a href="{% url 'blog:blog_create' %}" class="p-2 btn btn-secondary-link" style="color: #34373a">Добавить
        статью</a>
      {% else %}
      <a href="#" class="p-2 btn btn-secondary-link" style="color: #adb5bd">Добавить
        статью</a>
      {% endif %}
    </div>
  </div>
</div>

<!-- Контейнер содержащий карточки блогов -->
<div class="container-fluid col-8 justify-content-left">
  {% for blog in blog_list %}
  <div class="row">
    <div class="card-header" style="padding: 0px;">
      <div class="container col-12">
        {% if blog.preview %}
        <img src="{{ blog.preview.url }}" alt="{{ blog.preview }}" style="max-width: 800px;" />
        {% else %}
        <img src="/media/blog/blog_default.png" alt="{{ blog.preview }}" style="max-width: 800px;" />
        {% endif %}
      </div>
      <br />
      <div class="container text-start col-12">
        <h4 class="my-0 font-weight-normal text-black text-opacity-75 fw-bold">{{ blog.title }}</h4>
        <br />
        <p class="card-text">{{ blog.content|truncatechars:150 }}</p>
      </div>
      <br />
      <div class="container text-start col-12">
        <div class="row">
          <div class="col-3">
            <p style="color: #adb5bd; font-size: 0.9em;">Дата создания: {{ blog.created_at|date:'d.m.Y' }}</p>
          </div>
          <div class="col-4">
            <p style="color: #adb5bd;font-size: 0.9em;">Количество просмотров: {{ blog.views_counter }}</p>
          </div>
          <div class="col-4">
            {% if user.is_authenticated %}
            <div class="btn-group">
              <a href="{% url 'blog:blog_detail' blog.pk %}" class="p-2 btn btn-dark-link" role="button"
                style="color: #34373a;">Подробнее</a>
              <a href="{% url 'blog:blog_create' blog.pk %}" class="p-2 btn btn-dark-link" role="button"
                style="color: #34373a;">Редактировать</a>
              <a href="{% url 'blog:blog_confirm_delete' blog.pk %}" class="p-2 btn btn-dark-link" role="button"
                style="color: #34373a;">Удалить</a>
            </div>
            {% else %}
            <div class="btn-group">
              <a href="#" class="p-2 btn btn-secondary-link" role="button" style="color: #adb5bd;">Подробнее</a>
              <a href="#" class="p-2 btn btn-secondary-link" role="button" style="color: #adb5bd;">Редактировать</a>
              <a href="#" class="p-2 btn btn-secondary-link" role="button" style="color: #adb5bd;">Удалить</a>
            </div>
            {% endif %}
          </div>
        </div>

      </div>
    </div>
  </div>
  <br />
  <br />
  {% endfor %}
</div>
<!--  -->
{% endblock %}