blog/urls.py
# blog urls.py

from django.urls import path
from blog.views import BlogListView, BlogDetailView, BlogCreateView, BlogUpdateView, BlogDeleteView

app_name = 'blog'

urlpatterns = [
    path("blog_list/", BlogListView.as_view(), name="blog_list"),
    path("blog/<int:pk>/", BlogDetailView.as_view(), name="blog_detail"),
    path("blog/create", BlogCreateView.as_view(), name="blog_create"),
    path("blog/<int:pk>/update", BlogUpdateView.as_view(), name="blog_create"),
    path("blog/<int:pk>/delete", BlogDeleteView.as_view(), name="blog_confirm_delete"),
]

catalog/urls.py
# catalog/urls.py.

from django.urls import path
from catalog.apps import CatalogConfig
from catalog.views import (
    ProductDetailView,
    ProductListView,
    ProductCreateView,
    ProductUpdateView,
    ProductDeleteView,
    CategoryCreateView,
)


app_name = CatalogConfig.name

urlpatterns = [
    path("", ProductListView.as_view(), name="product_list"),
    path("product_detail/<int:pk>", ProductDetailView.as_view(), name="product_detail"),
    path("product_form/", ProductCreateView.as_view(), name="product_create"),
    path("product_form/<int:pk>/", ProductUpdateView.as_view(), name="product_update"),
    path("product_confirm_delete/<int:pk>/", ProductDeleteView.as_view(), name="product_delete"),
    path("category_form/", CategoryCreateView.as_view(), name="category_create"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("catalog.urls", namespace="catalog")),
    path("blog/", include("blog.urls", namespace="blog")),
    path("users/", include("users.urls", namespace="users")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users.views import UserRegisterView, UserLoginView, custom_logout, UserUpdateView
from users.apps import UsersConfig

app_name = UsersConfig.name

urlpatterns = [
    path("register/", UserRegisterView.as_view(), name="register"),
    path("login/", UserLoginView.as_view(template_name="users/login.html"), name="login"),
    path("logout/", custom_logout, name="logout"),
    path("user/<int:pk>/update/", UserUpdateView.as_view(), name="user_update"),
]

templates/base.html
<!-- base.html -->
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>
    {% block title %}
    Skystore
    {% endblock %}
  </title>
  <!-- Подключение Bootstrap CSS -->
  <link rel="stylesheet" type="text/css" href="/static/css/bootstrap.min.css" />
</head>

<body>
  <div class="container">
    <!-- Блок для размещения основного контента -->
    {% block content %}

    {% endblock %}
    <!--  -->

    <!-- Footer -->
    <footer class="pt-4 my-md-5 pt-md-5 border-top">
      <div class="row">
        <div class="col-12 col-md">
          SkyStore
          <small class="d-block mb-3 text-muted">&copy; 2023</small>
        </div>
        <div class="col-6 col-md">
          <h5>Категории</h5>
          <ul class="list-unstyled text-small">
            <li>
              <a class="text-muted" href="#">Рассылки</a>
            </li>
            <li>
              <a class="text-muted" href="#">Телеграм боты</a>
            </li>
            <li>
              <a class="text-muted" href="#">Полезные утилиты</a>
            </li>
            <li>
              <a class="text-muted" href="#">Веб-приложения</a>
            </li>
            <li>
              <a class="text-muted" href="#">Микросервисы</a>
            </li>
          </ul>
        </div>
        <div class="col-6 col-md">
          <h5>Дополнительно</h5>
          <ul class="list-unstyled text-small">
            <li>
              <a class="text-muted" href="{% url 'blog:blog_list' %}">Мы пишем</a>
            </li>
          </ul>
        </div>
        <div class="col-6 col-md">
          <h5>О нас</h5>
          <ul class="list-unstyled text-small">
            <li>
              <a class="text-muted" href="/contacts/">Контакты</a>
            </li>
          </ul>
        </div>
      </div>
    </footer>
    <!--  -->
  </div>

  <!-- Подключение Bootstrap JS -->
  <script src="/static/js/bootstrap.bundle.min.js"></script>
</body>

</html>

templates/header.html
<!-- header.html -->
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Skystore</title>
  <link rel="stylesheet" type="text/css" href="/static/css/bootstrap.min.css" />
</head>

templates/navbar.html
<!-- navbar.html -->
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Skystore</h5>
    <nav class="ms-5 d-flex justify-content-center flex-grow-1 gap-3">
        <div class="btn-group" style="width: 50%;">
            <a class="p-2 btn btn-light" style="border-radius: 25px;"
                href="{% url 'catalog:product_list' %}">Каталог</a>
            <a class="p-2 btn btn-light" style="border-radius: 25px;" href="{% url 'blog:blog_list' %}">Блог</a>
        </div>
        <div class="btn-group justify-content-end" style="width: 20%;">
            {% if user.is_authenticated %}
            {% csrf_token %}
            <a href="{% url 'users:logout' %}" class="p-2 btn btn-secondary-link"
                style="color: #34373a; font-size: 0.9rem;">Выйти</a>
            <a href="{% url 'users:user_update' user.pk %}"">
                <img src=" {{ user.avatar.url }}" alt="{{ user.username }}" class="rounded-circle"
                style="max-width: 18%" />
            </a>
            {% else %}
            <a href="{% url 'users:register' %}" class="p-2 btn btn-secondary-link"
                style="color: #34373a; font-size: 0.9rem;">Регистрация</a>
            <a href="{% url 'users:login' %}" class="p-2 btn btn-secondary-link"
                style="color: #34373a; font-size: 0.9rem;">Войти</a>
            {% endif %}
        </div>
    </nav>
</div>