blog/urls.py
# blog urls.py

from django.urls import path
from blog.views import BlogListView, BlogDetailView, BlogCreateView, BlogUpdateView, BlogDeleteView

app_name = 'blog'

urlpatterns = [
    path("blog_list/", BlogListView.as_view(), name="blog_list"),
    path("blog/<int:pk>/", BlogDetailView.as_view(), name="blog_detail"),
    path("blog/create", BlogCreateView.as_view(), name="blog_create"),
    path("blog/<int:pk>/update", BlogUpdateView.as_view(), name="blog_create"),
    path("blog/<int:pk>/delete", BlogDeleteView.as_view(), name="blog_confirm_delete"),
]

catalog/urls.py
# catalog/urls.py.

from django.urls import path
from catalog.apps import CatalogConfig
from catalog.views import (
    ProductDetailView,
    ProductListView,
    ProductCreateView,
    ProductUpdateView,
    ProductDeleteView,
    CategoryCreateView,
)


app_name = CatalogConfig.name

urlpatterns = [
    path("", ProductListView.as_view(), name="product_list"),
    path("product_detail/<int:pk>", ProductDetailView.as_view(), name="product_detail"),
    path("product_form/", ProductCreateView.as_view(), name="product_create"),
    path("product_form/<int:pk>/", ProductUpdateView.as_view(), name="product_update"),
    path("product_confirm_delete/<int:pk>/", ProductDeleteView.as_view(), name="product_delete"),
    path("category_form/", CategoryCreateView.as_view(), name="category_create"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("catalog.urls", namespace="catalog")),
    path("blog/", include("blog.urls", namespace="blog")),
    path("users/", include("users.urls", namespace="users")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models


class Category(models.Model):
    """Модель таблицы Категории [товаров]."""

    name = models.CharField(max_length=100, verbose_name="Наименование категории")
    description = models.TextField(verbose_name="Описание")

    def __repl__(self) -> str:
        """Строковое представление для разработчиков."""
        return "%s %s %s" % (self.__class__, self.name, self.description)

    def __str__(self) -> str:
        """Общее строковое представление."""
        return "%s" % self.name

    class Meta:
        verbose_name = "Категория товара"
        verbose_name_plural = "Категории товаров"
        ordering = [
            "name",
        ]


class Product(models.Model):
    """Модель таблицы Товар."""

    product = models.CharField(max_length=150, verbose_name="Наименование товара")
    description = models.TextField(verbose_name="Описание")
    image = models.ImageField(verbose_name="Изображение", blank=True, null=True, upload_to="catalog/")
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name="goods")
    price = models.FloatField(null=False, default=1.0, verbose_name="Цена товара")
    created_at = models.DateField(verbose_name="Дата производства")
    changed_at = models.DateField(verbose_name="Дата последнего изменения")
    views_counter = models.PositiveIntegerField(default=0, verbose_name="Количество просмотров")

    def __repl__(self) -> str:
        """Строковое представление для разработчиков."""
        return "%s %s %s %s %s" % (self.__class__, self.product, self.category, self.price, self.created_at)

    def __str__(self) -> str:
        """Общее строковое представление."""
        return "%s %s" % (self.product, self.price)

    class Meta:
        verbose_name = "Товар"
        verbose_name_plural = "Товары"
        ordering = [
            "product",
            "price",
        ]


class Contact(models.Model):
    """Класс для создания модели хранения контактных данных."""

    first_name = models.CharField(max_length=35, blank=False, null=False, verbose_name="Имя")
    last_name = models.CharField(max_length=50, blank=False, null=False, verbose_name="Фамилия")
    phone = models.CharField(max_length=15, blank=False, null=False, verbose_name="Телефон")
    message = models.TextField(verbose_name="Сообщение")

    def __repr__(self) -> str:
        """Строковое представление для разработчиков."""
        return "%s %s %s %s %s" % (self.__class__, self.first_name, self.last_name, self.phone, self.message)

    def __str__(self) -> str:
        """Общее строковое представление."""
        return "%s %s %s" % (self.first_name, self.last_name, self.phone)

    class Meta:
        verbose_name = "Контакт"
        verbose_name_plural = "Контакты"
        ordering = ["first_name", "last_name"]

catalog/forms.py
"""
Формы для ввода данных.
"""

import os

from blog.mixins import StyledFormMixin
from django import forms
from django.core.exceptions import ValidationError
from dotenv import load_dotenv

from catalog.models import Category, Product

load_dotenv()


class CategoryForm(StyledFormMixin, forms.ModelForm):
    """Форма для ввода данных о категории товаров."""

    class Meta:
        model = Category
        fields = "__all__"
        labels = {
            "name": "Наименование категории",
            "description": "Описание",
        }

    def clean(self):
        forbidden_words = os.getenv("FORBIDDEN_WORDS").split(",")
        cleaned_data = super().clean()

        cleaned_name = cleaned_data.get("name").split()
        for word in cleaned_name:
            if word.lower() in forbidden_words:
                self.add_error(
                    "name",
                    "Поле с наименованием категории содержит запрещённое слово %s." % word,
                )
                break

        cleaned_description = cleaned_data.get("description").split()
        for word in cleaned_description:
            if word.lower() in forbidden_words:
                self.add_error(
                    "description",
                    "Поле с описанием категории содержит запрещённое слово %s." % word,
                )
                break

        return cleaned_data


class ProductForm(StyledFormMixin, forms.ModelForm):
    """
    Форма для ввода данных о продукте.
    """

    class Meta:
        model = Product
        fields = "__all__"
        labels = {
            "name": "Название",
            "description": "Описание",
            "image": "Изображение",
            "category": "Категория",
            "price": "Цена",
            "created_at": "Дата производства",
            "changed_at": "Дата последнего изменения",
            "views_counter": "Количество просмотров",
        }

    def clean_price(self):
        """Проверяет, что введена неотрицательная цена."""
        cleaned_price = self.cleaned_data.get("price")
        if cleaned_price < 0:
            raise ValidationError("Вы указали недопустимое значение цены! Цена не может быть отрицательной!")

        return cleaned_price

    def clean_image_format(self):
        """
        Проверяет, что загружаемое изображение продукта в формате .jpg или .png.
        """
        image = self.cleaned_data.get("image")
        if image:
            valid_extensions = [".jpg", ".jpeg", ".png"]
            ext = os.path.splitext(image.name)[1].lower()
            if ext not in valid_extensions:
                raise ValidationError("Допустимые форматы изображений: .jpg, .jpeg, .png.")

        return image

    def clean_image_size(self):
        """
        Проверяет, что загружаемый файл изображения не превышает 5 МБ.
        """
        image = self.cleaned_data.get("image")
        max_size = 5 * 1024 * 1024  # 5 MБ

        if image and image.size > max_size:
            raise ValidationError("Размер изображения не должен превышать 5 МБ.")

        return image

    def clean(self):
        """Проверяет, что указанные поля формы не содержат запрещённые слова."""
        forbidden_words = os.getenv("FORBIDDEN_WORDS").split(",")
        cleaned_data = super().clean()

        cleaned_product = cleaned_data.get("product").split()
        for word in cleaned_product:
            if word.lower() in forbidden_words:
                self.add_error(
                    "product",
                    "Поле с наименованием продукта содержит запрещённое слово %s." % word,
                )
                break

        cleaned_description = cleaned_data.get("description").split()
        for word in cleaned_description:
            if word.lower() in forbidden_words:
                self.add_error(
                    "description",
                    "Поле с описанием продукта содержит запрещённое слово %s." % word,
                )
                break

        return cleaned_data

catalog/views.py
"""
Контроллеры, определённые внутри приложения catalog.
"""

import logging

from django.urls import reverse_lazy
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
)
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.mail import send_mail
from dotenv import load_dotenv

from catalog.forms import CategoryForm, ProductForm
from catalog.models import Category, Product

load_dotenv()

logger = logging.getLogger("catalog")
logger.setLevel(logging.DEBUG)
handler = logging.FileHandler("catalog/logs/reports.log", "a", "utf-8")
handler.setFormatter(logging.Formatter("%(asctime)s - %(name)s - %(levelname)s: %(message)s"))
logger.addHandler(handler)


# ---- Определяем набор CRUD-операций для модели Category ----
#
class CategoryCreateView(LoginRequiredMixin, CreateView):
    """Определяет отображение добавления категории."""

    model = Category
    context_object_name = "category"
    form_class = CategoryForm
    success_url = reverse_lazy("catalog:product_list")

    def form_valid(self, form):
        """Дополнительная обработка перед сохранением формы."""
        self.object = form.save()  # Сохраняем объект формы в базу
        logger.info("Категория продукта '%s' успешно создана." % self.object.name)
        return super().form_valid(form)

    def form_invalid(self, form):
        """Обработка в случае неверной формы."""
        logger.warning("Ошибка при создании категории продукта: %s" % form.errors)
        return super().form_invalid(form)


# ---- Определяем набор CRUD-операций для модели Product ----
#
class ProductListView(ListView):
    """Определяет отображение страницы со списком продуктов."""

    model = Product
    context_object_name = "product_list"


class ProductDetailView(LoginRequiredMixin, DetailView):
    """Определяет отображение детализации (характеристик) продукта."""

    model = Product
    context_object_name = "product"

    def get_object(self, queryset=None):
        """Проверяет количество просмотров статьи и отправляет уведомление администратору."""
        self.object = super().get_object(queryset)
        self.object.views_counter += 1

        # Отправлять уведомление администратору, если количество просмотров превысило 100
        if self.object.views_counter >= 100:
            logger.info("Количество просмотров превысило %s." % self.object.views_counter)
            self.send_info_email("stasm226@gmail.com")
            logger.info("Информационное сообщение отправлено на адрес %s." % "stasm226@gmail.com")

        self.object.save()

        return self.object

    def send_info_email(self, user_email):
        """Отправляет сообщение на email пользователя при успешной регистрации."""
        subject = "Новое достижение!"
        message = "Количество просмотров превысило 100: %s" % self.object.views
        from_email = "stasm226@gmail.com"
        recipients = ["stasm226@gmail.com"]
        send_mail(subject, message, from_email, recipients)


class ProductCreateView(LoginRequiredMixin, CreateView):
    """Определяет отображение добавления продукта."""

    model = Product
    form_class = ProductForm
    success_url = reverse_lazy("catalog:product_list")

    def form_valid(self, form):
        """Дополнительная обработка перед сохранением формы."""
        self.object = form.save()  # Сохраняем объект формы в базу
        logger.info("Продукт '%s' успешно создан." % self.object.product)
        return super().form_valid(form)

    def form_invalid(self, form):
        """Обработка в случае неверной формы."""
        logger.warning("Ошибка при создании продукта: %s" % form.errors)
        return super().form_invalid(form)


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    """Определяет отображение обновления продукта."""

    model = Product
    # fields = "__all__"
    form_class = ProductForm
    success_url = reverse_lazy("catalog:product_list")

    def form_valid(self, form):
        """Дополнительная обработка перед сохранением формы."""
        self.object = form.save()  # Сохраняем объект формы в базу
        logger.info("Продукт '%s' успешно обновлён." % self.object.product)
        return super().form_valid(form)

    def form_invalid(self, form):
        """Обработка в случае неверной формы."""
        logger.warning("Ошибка при обновлении продукта: %s" % form.errors)
        return super().form_invalid(form)


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    """Определяет отображение удаления продукта."""

    model = Product
    form_class = ProductForm
    context_object_name = "product"
    success_url = reverse_lazy("catalog:product_list")

    def post(self, request, *args, **kwargs):
        """Переопределение метода POST для вызова delete."""
        logger.info("Удаление продукта через POST-запрос.")
        return self.delete(request, *args, **kwargs)

    def delete(self, request, *args, **kwargs):
        """Переопределение метода delete для логирования."""
        product = self.get_object()
        logger.info("Продукт '%s' успешно удалён." % product.product)
        return super().delete(request, *args, **kwargs)

catalog/templates/catalog/category_form.html
<!-- category_form.html -->
{% extends 'base.html' %}
{% block title %} Skystore - добавить категорию товара {% endblock %}
{% block content %}
  {% include 'header.html' %}
  {% include 'navbar.html' %}
  <div class="container">
    <div class="row" style="align-items: center; justify-content: center">
      <div class="col-6">
        <form class="row" method="post" enctype="multipart/form-data">
          <div class="card">
            <div class="card-body">
              {% csrf_token %}
              {{ form.non_field_error }}
              {{ form.as_p }}
            </div>
            <div class="btn-group">
              <button type="submit" class="btn btn-primary">Сохранить</button>
              <a href="{% url 'catalog:product_list' %}" class="btn btn-secondary">Отменить</a>
            </div>
            <br/>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

catalog/templates/catalog/product_confirm_delete.html
<!-- product_confirm_delete.html -->
{% extends 'base.html' %} {% block title %} Skystore - удалить товар {% endblock %} {% block content %} {% include
'header.html' %} {% include 'navbar.html' %}
<div class="container">
    <div class="row" style="align-items: center; justify-content: center">
        <div class="col-6">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="card">
                    <div class="card-body">
                        {% if product.image %}
                        <img src="{{ product.image.url }}" alt="{{ product.product }}" style="max-width: 400px" />
                        {% else %}
                        <img src="/media/blog/blog_default.png" alt="{{ product.product }}" style="max-width: 400px" />
                        {% endif %}
                        <h2>{{ product.product }}</h2>
                        <h2>Удалить карточку товара?</h2>
                        {% csrf_token %}
                    </div>
                    <div class="btn-group">
                        <button type="submit" class="btn btn-danger">Удалить</button>
                        <a href="{% url 'catalog:product_list' %}" class="btn btn-secondary">Отменить</a>
                    </div>
                    <br />
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_detail.html
<!-- product_detail.html -->
{% extends 'base.html' %}
{% block title %}
  Skystore
{% endblock %}
{% block content %}
  {% include 'header.html' %}
  {% include 'navbar.html' %}

  <div class="container col-8">
    <div class="container-lg-fluid mt-5 text-center"
         style="background-color: #f8f9fa; padding: 10px; border-radius: 10px;">
      <div class="container-fluid">
        {% if product.image %}
          <img src="{{ product.image.url }}" alt="{{ product.product }}" style="max-height: 200px;"/>
        {% else %}
          <img src="/media/catalog/skystore_default.jpg" alt="{{ product.product }}" style="max-height: 200px;"/>
        {% endif %}
      </div>
      <div class="container-lg-fluid text-body-secondary">
        <br/>
        <h5 class="my-0 font-weight-normal text-black text-opacity-75 fw-bold">{{ product.product }}</h5>
        <p class="fw-bold" style="font-size: 0.9em;">{{ product.description }}</p>
        <p style="font-size: 0.9em;">Цена: {{ product.price }} руб</p>
        <p style="font-size: 0.9em;">Дата производства: {{ product.created_at|date:'d.m.Y' }}</p>
        <p style="font-size: 0.9em;">Категория: {{ product.category.name }} - {{ product.category.description }}</p>
        <p style="font-size: 0.9em;">Количество просмотров: {{ product.views_counter }}</p>
        <br/>
        <div class="btn-group">
          <button type="button" class="btn btn-primary">Добавить в корзину</button>
          <a href="{% url 'catalog:product_list' %}" class="btn btn-secondary">Вернуться</a>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

catalog/templates/catalog/product_form.html
<!-- product_form.html -->
{% extends 'base.html' %}
{% block title %} Skystore - добавить товар {% endblock %}
{% block content %}
  {% include 'header.html' %}
  {% include 'navbar.html' %}
  <div class="container">
    <div class="row" style="align-items: center; justify-content: center">
      <div class="col-6">
        <form class="row" method="post" enctype="multipart/form-data">
          <div class="card">
            <div class="card-body">
              {% if product.image %}
                <img src="{{ product.image.url }}" alt="{{ product.product }}" style="max-width: 400px"/>
              {% endif %}
              {% csrf_token %}
              {{ form.non_field_error }}
              {{ form.as_p }}
            </div>
            <div class="btn-group">
              <button type="submit" class="btn btn-primary">Сохранить</button>
              <a href="{% url 'catalog:product_list' %}" class="btn btn-secondary">Отменить</a>
            </div>
            <br/>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

catalog/templates/catalog/product_list.html
<!-- product_list.html -->
{% extends 'base.html' %}
{% block title %}
Skystore
{% endblock %}
{% block content %}
{% include 'header.html' %}
{% include 'navbar.html' %}

<!-- Заголовок страницы -->
<div class="pricing-header px-3 py-3 pt-md-1 pb-md-4 mx-auto text-center">
  <div class="row">
    <div class="col-8">
      <p class="text-start" style="font-size: 1.2em;">Отличный вариант что-то купить или что-то продать</p>
    </div>
    {% if user.is_authenticated %}
    <div class="col-2">
      <a class="p-2 btn btn-secondary-link" style="color: #34373a" href="{% url 'catalog:category_create' %}">Добавить
        категорию</a>
    </div>
    <div class="col-2">
      <a class="p-2 btn btn-secondary-link" style="color: #34373a" href="{% url 'catalog:product_create' %}">Добавить
        товар</a>
    </div>
    {% else %}
    <div class="col-2">
      <a href="#" class="p-2 btn btn-secondary-link" style="color: #adb5bd">Добавить категорию</a>
    </div>
    <div class="col-2">
      <a href="#" class="p-2 btn btn-secondary-link" style="color: #adb5bd">Добавить товар</a>
    </div>
    {% endif %}
  </div>
</div>

<!-- Контейнер содержащий карточки товаров -->
<div class="container text-center">
  <div class="row">
    {% for product in product_list %}
    <div class="col-4 justify-center">
      <!-- Карточка товара -->
      <div class="card-header"
        style="background-color: #f8f9fa; padding: 5px; border-radius: 5px; box-shadow: 5px 5px 15px rgba(0, 0, 0, 0.3);">
        <div class="justify-content-center">
          {% if product.image %}
          <img src="{{ product.image.url }}" alt="{{ product.product }}" style="max-height: 200px;" />
          {% else %}
          <img src="/media/catalog/skystore_default.jpg" alt="{{ product.product }}" style="max-height: 200px;" />
          {% endif %}
        </div>
        <hr style="border: none; height: 2px; background-color: #000;">
        <h5 class="my-0 font-weight-normal text-black text-opacity-75 fw-bold">{{ product.product|truncatechars:30 }}
        </h5>
        <ul class="list-group-horizontal-sm mt-3 mb-4 text-start m-3">
          <li class="fw-bold" style="font-size: 0.9em;">{{ product.description|truncatechars:30 }}</li>
          <li style="font-size: 0.9em;">Категория: {{ product.category.name }}</li>
          <li style="font-size: 0.9em;">Дата производства: {{ product.created_at|date:'d.m.Y' }}</li>

          <li>Количество просмотров: {{ product.views_counter }}</li>
        </ul>
        <h5 class="my-0 font-weight-normal text-black text-opacity-75 fw-bold">{{ product.price }} руб</h5>
        <br />
        {% if user.is_authenticated %}
        <div class="btn-group">
          <a href="{% url 'catalog:product_detail' product.pk %}" class="p-2 btn btn-dark-link" role="button"
            style="color: #34373a;">Подробнее</a>
          <a href="{% url 'catalog:product_update' product.pk %}" class="p-2 btn btn-dark-link" role="button"
            style="color: #34373a;">Редактировать</a>
          <a href="{% url 'catalog:product_delete' product.pk %}" class="p-2 btn btn-dark-link" role="button"
            style="color: #34373a;">Удалить</a>
        </div>
        {% else %}
        <div class="btn-group">
          <a href="#" class="p-2 btn btn-secondary-link" role="button" style="color: #adb5bd;">Подробнее</a>
          <a href="#" class="p-2 btn btn-secondary-link" role="button" style="color: #adb5bd;">Редактировать</a>
          <a href="#" class="p-2 btn btn-secondary-link" role="button" style="color: #adb5bd;">Удалить</a>
        </div>
        {% endif %}
      </div>
      <br />
      <!--  -->
    </div>
    {% endfor %}
  </div>
  <br />
</div>

{% endblock %}